  image: node:lts

  stages:
    - deploy

  deploy:
    stage: deploy
    only:
      - frontend
    before_script:
      - npm install -g vercel
      - npm install --force
    script:
      - npm run build
      - vercel --prod
    variables:
      VERCEL_TOKEN: aYVS1W8XA93K4qQDAOdTV7hn
      VERCEL_ORG_ID: team_yvgFinMriL5lSV7jlxCi59Qr
      VERCEL_PROJECT_ID: prj_hesboIGfVOJLvyy6pRi8iSwHQdLR
