  image: node:lts

  stages:
    - deploy

  deploy:
    stage: deploy
    only:
      - frontend
    variables:
      VERCEL_TOKEN: ghIWwCWnxvOhyxiLeuh8S70o
      VERCEL_ORG_ID: team_yvgFinMriL5lSV7jlxCi59Qr
      VERCEL_PROJECT_ID: prj_hesboIGfVOJLvyy6pRi8iSwHQdLR
    before_script:
      - npm install -g vercel
      - npm install --force
    script:
      - npm run build
      - vercel --prod --token "$VERCEL_TOKEN" --org "$VERCEL_ORG_ID" --project "$VERCEL_PROJECT_ID"