networks:
  fah:
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - auth-server
      - fah_frontend
    networks:
      - fah
  auth-server:
    build:
      context: ./FAH-auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - fah
  fah_frontend:
    build: 
      context: ./fah-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_API=${NEXT_PUBLIC_BASE_API}
    ports:
      - "3000:3000"

    depends_on:
      - auth-server
      - parsing_service
    
    env_file:
      - .env
    networks:
      - fah
  parsing_service:
    build:
      context: ./FAH_parsing_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - fah
    depends_on:
      - auth-server
  auth-db:
    container_name: auth_db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - fah
volumes:
  db-data:
