server:
  host: ${SERVER_HOST}
  port: 8083
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  host: ${DB_HOST}
  port: 5432
  name: "postgres"
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  ssl_mode: "disable"
  max_open_connections: 20
  max_idle_connections: 5
  connection_max_lifetime: 300s
