server:
  host: "87.228.102.156"
  port: 8081
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  host: "auth_db"
  port: 5432
  name: "postgres"
  user: "user"
  password: "actual_database_password_here"
  ssl_mode: "disable" 
  max_open_connections: 25
  max_idle_connections: 5
  connection_max_lifetime: 300s
  connection_timeout: 10s

jwt:
  access_token:
    secret: "${JWT_ACCESS_SECRET}"
    expiry: "15m"
    algorithm: "HS256"
  refresh_token:
    secret: "${JWT_REFRESH_SECRET}"
    expiry: "72h"
    algorithm: "HS256"

cookies:
  access_token:
    name: "accessToken"
    http_only: true
    secure: false 
    same_site: "default"
    path: "/"
    max_age: 900
  refresh_token:
    name: "refreshToken"
    http_only: true
    secure: false
    same_site: "default"
    path: "/auth"
    max_age: 604800

security:
  bcrypt:
    cost: 12 
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst: 10
  cors:
    allowed_origins:
      - "http://0.0.0.0:8081"
      - "http://localhost:3000"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
    allow_credentials: true
    max_age: 3600

