services:
  db:
    image: postgres:latest
    container_name: profile_db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profile_service
    ports:
      - "8083:8083"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
