server:
  host: "0.0.0.0"
  port: 8082
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
logging:
  level: "info"
  format: "json"
  console: true
  service_name: "parse-service"
  http_logging: true
  log_request_body: false 
  slow_request_ms: 2000